language: python

python:
    - 3.5

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py34-flake8
    - TOX_ENV=py35-flake8
    - TOX_ENV=precommit
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-djmaster
    - TOX_ENV=py32-dj18
    - TOX_ENV=py33-dj18
    - TOX_ENV=py34-dj18
    - TOX_ENV=py34-dj19
    - TOX_ENV=py34-djmaster
    - TOX_ENV=py35-dj19
    - TOX_ENV=py35-djmaster
    - TOX_ENV=pypy-dj18
    - TOX_ENV=pypy-dj19
    - TOX_ENV=pypy-djmaster
    - TOX_ENV=pypy3-dj18
    - TOX_ENV=pypy3-dj19
    - TOX_ENV=pypy3-djmaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py35-djmaster
    - env: TOX_ENV=py34-djmaster
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=pypy-djmaster
    - env: TOX_ENV=pypy3-djmaster

install:
  # virtualenv<14.0.0 is for Python 3.2 compatibility
  - pip install "virtualenv<14.0.0" tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
