language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.3.1

install:
  - pip install --use-mirrors -q Django==$DJANGO_VERSION PyYAML unittest2 flake8
  - python setup.py -q install

script:
  - flake8 --ignore=E501,W391 .
  - python setup.py test
